#!/bin/bash
pwiz.py -u gestioCI -P gestioCI -e mysql -t General_person,General_address,General_rel_human_addresses,Welcome_ic_person_membership,Welcome_ic_project_membership,auth_user,old_auth_user,Invoices_soci,General_rel_human_persons,public_form_registrationprofile,Welcome_ic_self_employed_rel_fees,Welcome_ic_self_employed_rel,insurances,Welcome_ic_self_employed_rel_licenses,Welcome_ic_document,Welcome_ic_document_type,Welcome_ic_licence,Welcome_ic_insurance,Welcome_ic_type,Welcome_ic_labor_contract,Welcome_ic_labor_contract_rel_fees,General_accountbank,Welcome_ic_stallholder -H localhost gestioCI_butterfly > models_new.py
autopep8 --experimental --max-line-length=80 models_new.py > models_new_autopep.py
mv models_new_autopep.py models_new.py
colordiff models.py models_new.py
